FROM python:3.12-bullseye

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends postgresql-client \
    && apt-get update && apt-get install -y xdg-utils \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/* \
    && apt-get update && apt-get install -y \
    build-essential \
    python3-dev \
    libpq-dev \
    gcc \
    && apt-get clean

RUN python -m pip install --upgrade pip
RUN python -m pip install --upgrade pip setuptools wheel

# Install Azure Developer CLI (azd)
#RUN curl -fsSL https://aka.ms/install-azd.sh | bash

WORKDIR /demo-code

COPY . .
#RUN python -m pip install .
RUN python -m pip install src/backend/.

RUN chmod +x src/backend/entrypoint.sh
EXPOSE 8000
EXPOSE 5173
#CMD ["bash", "-c", ". entrypoint.sh"]
CMD ["bash"]